subject
idsubject:int:1
subject:text:Основ
subject
idsubject:int:2
subject:text:Физика
subject
idsubject:int:3
subject:text:Социология
subject
idsubject:int:4
subject:text:Философия
subject
idsubject:int:5
subject:text:Физ-культура
subject
idsubject:int:6
subject:text:Выш.мат
subject
idsubject:int:7
subject:text:БЖЧ
subject
idsubject:int:8
subject:text:Англ.яз
subject
idsubject:int:9
subject:text:Фр.яз
subject
idsubject:int:10
subject:text:Нем.яз
subject
idsubject:int:11
subject:text:Бел.яз
subject
idsubject:int:12
subject:text:История Бел.
subject
idsubject:int:13
subject:text:Комп. графика
subject
idsubject:int:14
subject:text:Химия
subject
idsubject:int:15
subject:text:Обществоведение
subject
idsubject:int:16
subject:text:Основы БД
subject
idsubject:int:17
subject:text:ОБиП
subject
idsubject:int:18
subject:text:СТПМС
subject
idsubject:int:19
subject:text:ПиБСП
subject
idsubject:int:20
subject:text:ПиББДМС
